spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/calistrackdb_test}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=create-drop
spring.test.database.replace=none
# Désactiver l'email pour les tests
spring.mail.host=localhost
spring.mail.port=25
jwt.secret=${JWT_KEY:defaultSecretForTests}
jwt.expiration=${JWT_EXPIRATION:360000}
